### PR TITLE
Adding LICENSE

### PR DESCRIPTION
**Pull request by scorpionhiccup**

### CODE REVIEW

**Comment by kushalsingh007** [comment]
License :laughing:  ACK -- ... + Do you have the complete working code , Maybe we can add the final version of the app here too.

**Comment by kushalsingh007** [comment]
@scorpionhiccup : Although I have merged this, but should we be adding GPL License to Microsoft's code :confused: ?

**Comment by scorpionhiccup** [comment]
Well technically we are using their software to put licensing on our code on which we are putting GPL so it should be okay i think. Also I think Darshan has the complete working code.

**Comment by kushalsingh007** [comment]
Well you can't just do that ... Just because we wrote some parts of the code, does not mean that we can add a GPL licence to everything (well 99% in terms of LOC would be their code :stuck_out_tongue_winking_eye: )  ...But still ...Who cares I guess :wink: . Let's add the full code now :dancers:

**Pull request merged**
